//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi_GestionProyectos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prioridad
    {
        public Prioridad()
        {
            this.Proyecto = new HashSet<Proyecto>();
            this.Tarea = new HashSet<Tarea>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
    
        public virtual ICollection<Proyecto> Proyecto { get; set; }
        public virtual ICollection<Tarea> Tarea { get; set; }
    }
}
