//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi_GestionProyectos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Proyecto_Tarea_Grupo
    {
        public Proyecto_Tarea_Grupo()
        {
            this.Tarea = new HashSet<Tarea>();
        }
    
        public int idUsuario { get; set; }
        public int idProyecto { get; set; }
        public int idGrupo { get; set; }
        public Nullable<int> jefeGrupo { get; set; }
    
        public virtual Grupo Grupo { get; set; }
        public virtual Proyecto Proyecto { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual ICollection<Tarea> Tarea { get; set; }
    }
}
