//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi_GestionProyectos.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tarea
    {
        public int id { get; set; }
        public string nombre { get; set; }
        public System.DateTime fechaCreacion { get; set; }
        public Nullable<System.DateTime> fechaAsignacion { get; set; }
        public Nullable<int> tiempoEstimado { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> idUsuarioAsignado { get; set; }
        public int idProyecto { get; set; }
        public Nullable<int> idGrupo { get; set; }
        public int idEstado { get; set; }
        public int idPrioridad { get; set; }
        public string comentarios { get; set; }
        public string idUsuarioCreador { get; set; }
    
        public virtual EstadoTarea EstadoTarea { get; set; }
        public virtual Prioridad Prioridad { get; set; }
        public virtual Proyecto_Tarea_Grupo Proyecto_Tarea_Grupo { get; set; }
    }
}
